apiVersion: gcp.vaultongke.crossplane.io/v1alpha1
kind: Network
metadata:
  name: vault-on-gke-network
spec:
  id: vault-on-gke-network
  clusterRef:
    id: vault-on-gke-cluster
  compositionSelector:
    matchLabels:
      provider: GCP
